name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*' 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract Tag Name
      id: extract_tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build --build-arg VERSION=${{ env.tag }} -t ${{ secrets.DOCKER_USERNAME }}/doc2paperless:${{ env.tag }} -t ${{ secrets.DOCKER_USERNAME }}/doc2paperless:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/doc2paperless:${{ env.tag }}
        docker push ${{ secrets.DOCKER_USERNAME }}/doc2paperless:latest

    - name: Push readme.md to docker hub
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: peterevans/dockerhub-description
        readme-filepath: ./readme.md